development:
  secret_key_base: e3379badeb9a46a3490c13812e9501a37cf1ab90771a13709af3ba701c3ad72d0576e3aabf8c886b1090eda6035ca19bd56d57ae05a093d35341c0df24f0e1d9

test:
  secret_key_base: c7ebc5db8000e41bfdded0040e8b0290c0e3eacb6fcfcc43958dafffb42465df76e10a740d72120eb4b74a91820f635188310bf01977a9e1babfe5d8354fc983

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
